name: Company of the Future
favicon: null
layout_spectrum: 0.41948
typography_spectrum: 0.54352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffa900'
    - '#00d270'
    - '#ff3a00'
    - '#0084bb'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
