name: Company of the Future
favicon: null
layout_spectrum: 0.14568567206151783
typography_spectrum: 0.7789069060236216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6097165595274419
  lightness: 0.29809271451085806
  saturation: 0.5581573694944382
  rhythmicContrast: 0.54895930737257
purpose: []
